services:
  fotg-api:
    env_file:
      - ./.env
    environment:
      - START_CMD=start
      - DB_HOST_NAME=fotg-db
    ports: []
    networks:
      - fotg-network
      - caddy-net
    volumes:
      - thumbnails:/usr/src/app/public/thumbnails

  fotg-db:
    volumes:
      - mongodata:/data/db

  db-seed:
    profiles:
      - seed

networks:
  fotg-network:
  caddy-net:
    external: true

volumes:
  mongodata:
  thumbnails:
