#!/bin/bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
unset npm_config_prefix
nvm install

printf "installing dependencies...\n"

if ! npm install; then
  printf "dependency installation failed\n"
  exit 1
fi

printf '\nrunning build...\n'
if ! npm run --silent build; then
  printf '\nthere was an error while building\n'
  exit 1
fi

printf '\nbuild completed!\n'

DEPLOY_DIR="/var/www/html/theunderempire.com/public_html/foodofthegods"

printf '\nremoving old build\n'
if ! rm -rf "$DEPLOY_DIR"/*; then
  printf "\nrm of old site files failed\n"
  exit 1
fi

printf '\ndeploying new build...\n'
if mv ./dist/* "$DEPLOY_DIR"/ && rm -rf ./dist && cp .htaccess "$DEPLOY_DIR"/.htaccess; then
  printf '\ndeploy completed!\n'
else
  printf '\nthere was an error while deploying\n'
fi
